import 'package:flutter/material.dart';
import 'package:flutterapp/flutter_20login_20app/generatedloginpagewidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/flutter_20login_20app/generatedloginpagewidget/generated/GeneratedMoon1Widget.dart';
import 'package:flutterapp/flutter_20login_20app/generatedloginpagewidget/generated/GeneratedBackgroundbyPexels1Widget.dart';
import 'package:flutterapp/flutter_20login_20app/generatedloginpagewidget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/flutter_20login_20app/generatedloginpagewidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/flutter_20login_20app/generatedloginpagewidget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/flutter_20login_20app/generatedloginpagewidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/flutter_20login_20app/generatedloginpagewidget/generated/GeneratedForgotYourPasswordWidget.dart';
import 'package:flutterapp/flutter_20login_20app/generatedloginpagewidget/generated/GeneratedLoginIntoYourAccountWidget.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -672.0,
                top: -8.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 853.0,
                child: GeneratedBackgroundbyPexels1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 820.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 126.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 123.0,
                child: GeneratedMoon1Widget(),
              ),
              Positioned(
                left: 88.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 27.0,
                child: GeneratedLoginIntoYourAccountWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 48.0,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 48.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 48.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 24.0,
                child: GeneratedForgotYourPasswordWidget(),
              )
            ]),
      ),
    ));
  }
}
